"""table added

Revision ID: 187a946db127
Revises: 81f9723a4fb5
Create Date: 2025-01-15 14:30:50.343684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '187a946db127'
down_revision: Union[str, None] = '81f9723a4fb5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('blogs', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('blogs', 'body',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('profiles', 'date_of_birth',
               existing_type=sa.DATE(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_unique_constraint(None, 'users', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('profiles', 'date_of_birth',
               existing_type=sa.String(),
               type_=sa.DATE(),
               existing_nullable=True)
    op.alter_column('blogs', 'body',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('blogs', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
